services:
  - name: web
    env:
      - key: SECRET_KEY
        # Add your Django SECRET_KEY value here
        value: "django-insecure-vi8u#u^v3e2t3ar2)s8b%tj2kt()a%wqtkalt7bpk#dhw4c_ix"
    buildCommand: python manage.py collectstatic --noinput
    staticPublishPath: static
    start_command: "gunicorn shopciti.wsgi:application --bind 0.0.0.0:$PORT"
    health_check_path: "/"

databases:
  - name: my-database
    type: postgresql
    plan: free
    config:
      database: db_shopciti_0rc7
      user: db_shopciti_0rc7_user
      password: qUshIywz95TVJQkrPuPC6jBiWZYKitoi
      host: dpg-ckj68eomccbs73e00f30-a  # Replace with your PostgreSQL host
      port: 5432