# Generated by Django 2.2.24 on 2023-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subscription_level',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
