# Generated by Django 4.2.7 on 2024-01-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0004_customuser_address_customuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='review',
            name='store',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='store',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreProfile',
        ),
    ]
