# Generated by Django 4.1.2 on 2024-05-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0005_size_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
