# Generated by Django 4.2.7 on 2024-02-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0006_shop_vendorapplication_customuser_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='South Africa', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default='Shop name', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(default='000000000', max_length=20),
        ),
    ]
