# Generated by Django 4.1.2 on 2023-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='static/img/store_logo.png', upload_to='store_logos/'),
        ),
    ]
