# Generated by Django 4.2.7 on 2024-02-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0009_customuser_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='shop',
            new_name='shop_name',
        ),
    ]
