# Generated by Django 4.2.7 on 2024-02-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0011_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='shopciti_app.shop'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopciti_app.shop'),
        ),
    ]
