# Generated by Django 4.2.7 on 2024-02-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shopciti_app', '0012_product_shop_name_alter_customuser_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='shopciti_app.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shopciti_app.shop'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
