# Generated by Django 4.2.7 on 2024-02-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0013_remove_customuser_shop_name_remove_product_shop_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='shop',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='shop_name',
        ),
    ]
