# Generated by Django 4.2.7 on 2024-02-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0014_rename_shop_customuser_shop_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='shop_name',
            new_name='shop',
        ),
    ]
