# Generated by Django 4.2.7 on 2024-03-05 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0018_vendorapplication_delete_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
