# Generated by Django 4.2.7 on 2024-03-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0021_alter_product_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shop name', max_length=100)),
                ('contact_email', models.EmailField(default='example@gmail.com', max_length=100)),
                ('phone_number', models.CharField(default='000000000', max_length=20)),
                ('city', models.CharField(default='South Africa', max_length=100)),
                ('postal_code', models.CharField(default='000000000', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='shopciti_app.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shopciti_app.shop'),
        ),
    ]
