# Generated by Django 4.2.7 on 2024-03-05 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0022_shop_remove_product_added_by_customuser_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
