# Generated by Django 4.2.7 on 2024-03-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0031_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
