# Generated by Django 4.2.7 on 2024-03-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0032_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
