# Generated by Django 4.2.7 on 2024-03-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0035_customuser_logo_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
    ]
