# Generated by Django 4.2.7 on 2024-03-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0036_remove_customuser_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
    ]
