# Generated by Django 4.2.7 on 2024-03-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0039_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(default='', max_length=12),
        ),
    ]
