# Generated by Django 4.2.7 on 2024-03-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0040_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
