# Generated by Django 4.2.7 on 2024-03-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0041_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
