# Generated by Django 4.1.2 on 2024-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0044_product_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
