# Generated by Django 4.1.2 on 2024-05-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0045_remove_product_available_quantity_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
