# Generated by Django 4.1.2 on 2024-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0046_customuser_phone_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
