# Generated by Django 4.1.2 on 2024-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0048_customuser_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
