# Generated by Django 4.1.2 on 2024-05-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0049_remove_customuser_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
