# Generated by Django 4.1.2 on 2024-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0053_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
