# Generated by Django 4.1.2 on 2024-05-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0054_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
