# Generated by Django 4.1.2 on 2024-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0056_order_created_at_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
