# Generated by Django 4.1.2 on 2023-10-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0003_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
