# Generated by Django 4.1.2 on 2023-10-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopciti_app', '0008_alter_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='static/img/store_logo.jpg', upload_to='store_logos/'),
        ),
    ]
